/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krutna.testexercise;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    App application = new App();
  }
}
