/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krutna.testexercise;

public class App {

  public static void main(String[] args) {
    App application = new App();
  }
}
